#!/bin/bash

cat >> /home/oracle/.bash_profile <<EOF
ORACLE_BASE=/u01/app/oracle
export ORACLE_BASE

ORACLE_SID=ORCL
export ORACLE_SID

ORACLE_HOME=$ORACLE_BASE/product/12.1.0/dbhome_1
export ORACLE_HOME

PATH=$ORACLE_HOME/bin:$PATH
export PATH
EOF

mount -t tmpfs shmfs -o size=4g /dev/shm
chown -R oracle:oinstall /u01/app/oracle/oradata

date
echo "Creating database..."
su -s /bin/bash oracle -c "sqlplus /nolog @?/config/scripts/createdb.sql"
echo ""

date
echo "Creating password file..."
cd $ORACLE_HOME/dbs
su -s /bin/bash oracle -c "$ORACLE_HOME/bin/orapwd FILE=orapw$ORACLE_SID password=Password1"
echo ""

date
echo "Running catcdb.sql..."
cd $ORACLE_HOME/rdbms/admin
cp catcdb_int.sql catcdb-e.sql
echo "exit" >> catcdb.sql
su -s /bin/bash oracle -c "sqlplus / as sysdba @?/rdbms/admin/catcdb-e.sql | tee /tmp/catcdb.log" <<EOF
Password1
Password1
TEMP
EOF
rm catcdb.sql
echo ""

echo "Finalizing install and shutting down the database..."
su -s /bin/bash oracle -c "sqlplus / as sysdba @?/config/scripts/conf_finish.sql"
echo ""

date
echo "Create is done; commit the container now"
